name: example
version: "1.0"
config-version: 2
profile: dbt_firebird_example

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  example:
    staging:
      +materialized: view
    marts:
      +materialized: table
      +persist_docs:
        relation: true
        columns: true
