dbt_firebird_example:
  target: dev
  outputs:
    dev:
      type: firebird
      host: localhost
      port: 3050
      path: C:/dados/dbt_example.fdb   # ajuste para o caminho do SEU banco de teste
      user: SYSDBA
      password: masterkey
      charset: UTF8
      threads: 1
